export interface Location {
  name: string;
  code: string;
}

export const LOCATIONS_BY_COUNTRY: Record<string, Location[]> = {
  MZ: [
    { name: 'Maputo Cidade', code: 'MAPUTO_CIDADE' },
    { name: 'Maputo Província', code: 'MAPUTO_PROVINCIA' },
    { name: 'Gaza', code: 'GAZA' },
    { name: 'Inhambane', code: 'INHAMBANE' },
    { name: 'Sofala', code: 'SOFALA' },
    { name: 'Manica', code: 'MANICA' },
    { name: 'Tete', code: 'TETE' },
    { name: 'Zambézia', code: 'ZAMBEZIA' },
    { name: 'Nampula', code: 'NAMPULA' },
    { name: 'Niassa', code: 'NIASSA' },
    { name: 'Cabo Delgado', code: 'CABO_DELGADO' },
  ],
  BR: [
    { name: 'Acre', code: 'AC' },
    { name: 'Alagoas', code: 'AL' },
    { name: 'Amapá', code: 'AP' },
    { name: 'Amazonas', code: 'AM' },
    { name: 'Bahia', code: 'BA' },
    { name: 'Ceará', code: 'CE' },
    { name: 'Distrito Federal', code: 'DF' },
    { name: 'Espírito Santo', code: 'ES' },
    { name: 'Goiás', code: 'GO' },
    { name: 'Maranhão', code: 'MA' },
    { name: 'Mato Grosso', code: 'MT' },
    { name: 'Mato Grosso do Sul', code: 'MS' },
    { name: 'Minas Gerais', code: 'MG' },
    { name: 'Pará', code: 'PA' },
    { name: 'Paraíba', code: 'PB' },
    { name: 'Paraná', code: 'PR' },
    { name: 'Pernambuco', code: 'PE' },
    { name: 'Piauí', code: 'PI' },
    { name: 'Rio de Janeiro', code: 'RJ' },
    { name: 'Rio Grande do Norte', code: 'RN' },
    { name: 'Rio Grande do Sul', code: 'RS' },
    { name: 'Rondônia', code: 'RO' },
    { name: 'Roraima', code: 'RR' },
    { name: 'Santa Catarina', code: 'SC' },
    { name: 'São Paulo', code: 'SP' },
    { name: 'Sergipe', code: 'SE' },
    { name: 'Tocantins', code: 'TO' },
  ],
  PT: [
    { name: 'Lisboa', code: 'LISBOA' },
    { name: 'Porto', code: 'PORTO' },
    { name: 'Vila Nova de Gaia', code: 'VILA_NOVA_DE_GAIA' },
    { name: 'Amadora', code: 'AMADORA' },
    { name: 'Braga', code: 'BRAGA' },
    { name: 'Funchal', code: 'FUNCHAL' },
    { name: 'Coimbra', code: 'COIMBRA' },
    { name: 'Setúbal', code: 'SETUBAL' },
    { name: 'Aveiro', code: 'AVEIRO' },
    { name: 'Faro', code: 'FARO' },
  ],
  AO: [
    { name: 'Luanda', code: 'LUANDA' },
    { name: 'Benguela', code: 'BENGUELA' },
    { name: 'Huambo', code: 'HUAMBO' },
    { name: 'Lubango', code: 'LUBANGO' },
    { name: 'Kuito', code: 'KUITO' },
    { name: 'Malanje', code: 'MALANJE' },
    { name: 'Cabinda', code: 'CABINDA' },
  ],
  US: [
    { name: 'New York', code: 'NEW_YORK' },
    { name: 'Los Angeles', code: 'LOS_ANGELES' },
    { name: 'Chicago', code: 'CHICAGO' },
    { name: 'Miami', code: 'MIAMI' },
    { name: 'San Francisco', code: 'SAN_FRANCISCO' },
  ],
  CV: [
    { name: 'Praia', code: 'PRAIA' },
    { name: 'Mindelo', code: 'MINDELO' },
    { name: 'Espargos', code: 'ESPARGOS' },
  ],
  GW: [
    { name: 'Bissau', code: 'BISSAU' },
    { name: 'Bafatá', code: 'BAFATA' },
  ],
  ST: [
    { name: 'São Tomé', code: 'SAO_TOME' },
    { name: 'Trindade', code: 'TRINDADE' },
  ],
  ZA: [
    { name: 'Johannesburg', code: 'JOHANNESBURG' },
    { name: 'Cape Town', code: 'CAPE_TOWN' },
    { name: 'Durban', code: 'DURBAN' },
    { name: 'Pretoria', code: 'PRETORIA' },
  ],
};
