import { useState, useEffect } from 'react';
import { Navigate, useLocation } from 'react-router-dom';
import { useAuth } from '@/contexts/AuthContext';
import { useSubscription } from '@/hooks/useSubscription';
import { supabase } from '@/integrations/supabase/client';

interface ProtectedRouteProps {
  children: React.ReactNode;
}

export function ProtectedRoute({ children }: ProtectedRouteProps) {
  const { session, user, loading: authLoading } = useAuth();
  const { loading: subLoading, hasAccess, organization } = useSubscription();
  const location = useLocation();
  const [needsOnboarding, setNeedsOnboarding] = useState<boolean | null>(null);
  const [isSystemAdmin, setIsSystemAdmin] = useState<boolean | null>(null);

  // Check if user is a system admin (app owner)
  useEffect(() => {
    const checkSystemAdmin = async () => {
      if (!user) {
        setIsSystemAdmin(false);
        return;
      }
      
      const { data } = await supabase
        .from('user_roles')
        .select('role')
        .eq('user_id', user.id)
        .eq('role', 'proprietor')
        .maybeSingle();
      
      setIsSystemAdmin(!!data);
    };

    checkSystemAdmin();
  }, [user]);

  // Check for pending plan selection or onboarding
  useEffect(() => {
    const checkOnboarding = async () => {
      if (!user || !organization) {
        setNeedsOnboarding(null);
        return;
      }
      
      // Check if organization name is auto-generated (needs setup)
      const isAutoGenerated = organization.name.includes("'s Agency") || organization.name === 'Agency';
      setNeedsOnboarding(isAutoGenerated);
    };

    const checkPlanSelection = async () => {
      if (!user) return;
      
      // Get profile
      const { data: profile } = await supabase
        .from('profiles')
        .select('organization_id')
        .eq('id', user.id)
        .maybeSingle();
      
      if (!profile?.organization_id) {
        // No organization means needs to select plan
        return;
      }
      
      // Check if has active subscription
      const { data: subscription } = await supabase
        .from('subscriptions')
        .select('status')
        .eq('organization_id', profile.organization_id)
        .maybeSingle();
      
      // If no subscription or not active, may need plan selection
      // But allow if has organization with proper name (for webhook delay)
      if (!subscription || subscription.status === 'trialing') {
        // Check organization for trial
        const { data: org } = await supabase
          .from('organizations')
          .select('trial_ends_at, name')
          .eq('id', profile.organization_id)
          .single();
        
        // If trial is active or org has proper name, allow access
        if (org && new Date(org.trial_ends_at) > new Date()) {
          return;
        }
        if (org && !org.name.includes("'s Agency") && org.name !== 'Agency') {
          return;
        }
      }
    };

    if (!subLoading && organization) {
      checkOnboarding();
    } else if (!subLoading && !organization && isSystemAdmin === false) {
      // No organization and not system admin - needs onboarding
      setNeedsOnboarding(true);
      checkPlanSelection();
    }
  }, [user, organization, subLoading, isSystemAdmin]);

  // Show loading while checking auth
  if (authLoading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-background">
        <div className="text-center">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary mx-auto mb-4"></div>
          <p className="text-muted-foreground">Carregando...</p>
        </div>
      </div>
    );
  }

  // Redirect to auth if not logged in
  if (!session) {
    return <Navigate to="/auth" state={{ from: location }} replace />;
  }

  // Show loading while checking subscription and admin status
  if (subLoading || isSystemAdmin === null || (needsOnboarding === null && !isSystemAdmin)) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-background">
        <div className="text-center">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary mx-auto mb-4"></div>
          <p className="text-muted-foreground">Verificando...</p>
        </div>
      </div>
    );
  }

  // System admins trying to access /app/* routes - redirect to admin panel
  if (isSystemAdmin && location.pathname.startsWith('/app')) {
    return <Navigate to="/admin" replace />;
  }

  // System admins have full access to admin area
  if (isSystemAdmin) {
    return <>{children}</>;
  }

  // Redirect to onboarding if organization needs setup
  if (needsOnboarding) {
    return <Navigate to="/app/onboarding" replace />;
  }

  // Freemium model: all authenticated users with organization have access
  // Feature limitations are handled at the page/component level via usePlanLimits
  return <>{children}</>;
}
