import { useState, useEffect } from 'react';
import { Navigate, useLocation } from 'react-router-dom';
import { useAuth } from '@/contexts/AuthContext';
import { useSubscription } from '@/hooks/useSubscription';
import { supabase } from '@/integrations/supabase/client';

interface ProtectedRouteProps {
  children: React.ReactNode;
}

export function ProtectedRoute({ children }: ProtectedRouteProps) {
  const { session, user, loading: authLoading } = useAuth();
  const { loading: subLoading, hasAccess, organization } = useSubscription();
  const location = useLocation();
  const [needsOnboarding, setNeedsOnboarding] = useState<boolean | null>(null);
  const [isSystemAdmin, setIsSystemAdmin] = useState<boolean | null>(null);

  // Check if user is a system admin (app owner)
  useEffect(() => {
    const checkSystemAdmin = async () => {
      if (!user) {
        setIsSystemAdmin(false);
        return;
      }
      
      const { data } = await supabase
        .from('user_roles')
        .select('role')
        .eq('user_id', user.id)
        .eq('role', 'admin')
        .maybeSingle();
      
      setIsSystemAdmin(!!data);
    };

    checkSystemAdmin();
  }, [user]);

  useEffect(() => {
    const checkOnboarding = async () => {
      if (!user || !organization) {
        setNeedsOnboarding(null);
        return;
      }
      
      // Check if organization name is auto-generated (needs setup)
      const isAutoGenerated = organization.name.includes("'s Agency") || organization.name === 'Agency';
      setNeedsOnboarding(isAutoGenerated);
    };

    if (!subLoading && organization) {
      checkOnboarding();
    } else if (!subLoading && !organization && isSystemAdmin === false) {
      // No organization and not system admin - needs onboarding
      setNeedsOnboarding(true);
    }
  }, [user, organization, subLoading, isSystemAdmin]);

  // Show loading while checking auth
  if (authLoading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-background">
        <div className="text-center">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary mx-auto mb-4"></div>
          <p className="text-muted-foreground">Carregando...</p>
        </div>
      </div>
    );
  }

  // Redirect to auth if not logged in
  if (!session) {
    return <Navigate to="/auth" state={{ from: location }} replace />;
  }

  // Show loading while checking subscription and admin status
  if (subLoading || isSystemAdmin === null || (needsOnboarding === null && !isSystemAdmin)) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-background">
        <div className="text-center">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary mx-auto mb-4"></div>
          <p className="text-muted-foreground">Verificando...</p>
        </div>
      </div>
    );
  }

  // System admins have full access without organization/subscription checks
  if (isSystemAdmin) {
    return <>{children}</>;
  }

  // Redirect to onboarding if organization needs setup
  if (needsOnboarding) {
    return <Navigate to="/app/onboarding" replace />;
  }

  // Allow access to subscription page always (for subscription management)
  const isSubscriptionPage = location.pathname.includes('/subscription');
  
  // If no access and not on subscription, redirect to subscription page
  if (!hasAccess && !isSubscriptionPage) {
    return <Navigate to="/app/subscription" replace />;
  }

  return <>{children}</>;
}
