import { useState, useEffect } from 'react';
import { Navigate, useLocation } from 'react-router-dom';
import { useAuth } from '@/contexts/AuthContext';
import { useSubscription } from '@/hooks/useSubscription';
import { supabase } from '@/integrations/supabase/client';

interface ProtectedRouteProps {
  children: React.ReactNode;
}

export function ProtectedRoute({ children }: ProtectedRouteProps) {
  const { session, user, loading: authLoading } = useAuth();
  const { loading: subLoading, hasAccess, organization } = useSubscription();
  const location = useLocation();
  const [needsOnboarding, setNeedsOnboarding] = useState<boolean | null>(null);

  useEffect(() => {
    const checkOnboarding = async () => {
      if (!user || !organization) {
        setNeedsOnboarding(null);
        return;
      }
      
      // Check if organization name is auto-generated (needs setup)
      const isAutoGenerated = organization.name.includes("'s Agency") || organization.name === 'Agency';
      setNeedsOnboarding(isAutoGenerated);
    };

    if (!subLoading && organization) {
      checkOnboarding();
    }
  }, [user, organization, subLoading]);

  // Show loading while checking auth
  if (authLoading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-background">
        <div className="text-center">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary mx-auto mb-4"></div>
          <p className="text-muted-foreground">Carregando...</p>
        </div>
      </div>
    );
  }

  // Redirect to auth if not logged in
  if (!session) {
    return <Navigate to="/auth" state={{ from: location }} replace />;
  }

  // Show loading while checking subscription
  if (subLoading || needsOnboarding === null) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-background">
        <div className="text-center">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary mx-auto mb-4"></div>
          <p className="text-muted-foreground">Verificando...</p>
        </div>
      </div>
    );
  }

  // Redirect to onboarding if organization needs setup
  if (needsOnboarding) {
    return <Navigate to="/app/onboarding" replace />;
  }

  // Allow access to settings and subscription pages always (for subscription management)
  const isSettingsPage = location.pathname.includes('/settings');
  const isSubscriptionPage = location.pathname.includes('/subscription');
  
  // If no access and not on settings/subscription, redirect to upgrade
  if (!hasAccess && !isSettingsPage && !isSubscriptionPage) {
    return <Navigate to="/app/upgrade" replace />;
  }

  return <>{children}</>;
}
